import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/sections/header";
import Footer from "@/components/sections/footer";
import DownloadCv from "@/components/molecules/download-button";

export const metadata: Metadata = {
  title: "Arjun Jhukal | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-100">
        <Header />
        {children}
        <Footer />
        <DownloadCv />
      </body>
    </html>
  );
}
